### ISSUE TITLE
Additional Attributes

### ISSUE THREAD

**Issue by AleAltube** [sense-of-security/ADRecon#12]
Hi, first, thanks so much for making this code available!

Secondly, I’ve been struggling to add other attributes like user accounts’ “info”, the pivot tables don’t seem to like that... would it be possible to understand which lines would have to be modified to include other attributes for computer, group, and user objects without affecting any other part of the script?

Thanks again!

**Comment by prashant3535** [comment]
Hi,

Could you please share the attributes you are trying to add or the provide more information about the pivot table issue? I can easily add those attributes and push a commit to the repo.

If the problem is only with the pivot table, then the Get-ADRExcelPivotTable function (https://github.com/sense-of-security/ADRecon/blob/master/ADRecon.ps1#L3886) is where the issue might be. For the User and Computer Stats sheet in the excel, the Get-ADRExcelAttributeStats function (https://github.com/sense-of-security/ADRecon/blob/master/ADRecon.ps1#L4030).

**Comment by AleAltube** [comment]
Hey Prashant, is it feasible to have the mentioned attributes added? Can I help in any way?

**Comment by prashant3535** [comment]
Hi AleAltube,

It is feasible to add the attributes. Some attributes are already present as renamed as you already know. I'm working on something else at the moment and should be able to get to it over the weekend.

Thanks for your patience.

**Comment by prashant3535** [comment]
Hi AleAltude,

I've added the attributes as described below:

User Attributes:
[C] - Added as renamed field "Country"
[cn] - Already present as renamed field "Name"
[company] - Added
[givenName] - Added as renamed field "First Name"
[info] - Added
[sn] - Added as renamed field "Last Name"
[UserAccountControl] - Added
[sAMAccountName] - Already present as renamed field "UserName"

Added other attributes such as Department, Title, Manager, Mobile, etc.

TODO
[adDomain] -> This would have to be customized since it's not a native attribute (Optional)
[adForest] -> This would have to be customized since it's not a native attribute (Optional)

Computer Attributes:
[operatingSystemServicePack] - Already present as an Concatenated field "Operating System"
[operatingSystemType] - Already present as an Concatenated field "Operating System"
[operatingSystemVersion] - Already present as an Concatenated field "Operating System"
[sAMAccountName] (I think there is already a renamed attribute containing this value, but if possible it would be great if it can be added with its original attribute name as well) - Already present as renamed field "UserName"
[userAccountControl] - Added
TODO
[accountExpires]
[canonicalName]
[displayName]
[adDomain] -> This would have to be customized since it's not a native attribute (Optional)
[adForest] -> This would have to be customized since it's not a native attribute (Optional)

Group Attributes:
[samaccountname] (I think there is already a renamed attribute containing this value, but if possible it would be great if it can be added with its original attribute name as well) - Already present as renamed field "Name"
TODO
[adForest] -> This would have to be customized since it's not a native attribute (Optional)
[adDomain] -> This would have to be customized since it's not a native attribute (Optional)

**Comment by AleAltube** [comment]
Thanks so much for this, I’ll test it out tomorrow!

On 1 Dec 2018, at 23:03, prashant3535 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi AleAltude,

I've added the attributes as described below:

User Attributes:
[C] - Added as renamed field "Country"
[cn] - Already present as renamed field "Name"
[company] - Added
[givenName] - Added as renamed field "First Name"
[info] - Added
[sn] - Added as renamed field "Last Name"
[UserAccountControl] - Added
[sAMAccountName] - Already present as renamed field "UserName"
TODO
[adDomain] -> This would have to be customized since it's not a native attribute (Optional)
[adForest] -> This would have to be customized since it's not a native attribute (Optional)

Computer Attributes:
[operatingSystemServicePack] - Already present as an Concatenated field "Operating System"
[operatingSystemType] - Already present as an Concatenated field "Operating System"
[operatingSystemVersion] - Already present as an Concatenated field "Operating System"
[sAMAccountName] (I think there is already a renamed attribute containing this value, but if possible it would be great if it can be added with its original attribute name as well) - Already present as renamed field "UserName"
[userAccountControl] - Added
TODO
[accountExpires]
[canonicalName]
[displayName]
[adDomain] -> This would have to be customized since it's not a native attribute (Optional)
[adForest] -> This would have to be customized since it's not a native attribute (Optional)

Group Attributes:
[samaccountname] (I think there is already a renamed attribute containing this value, but if possible it would be great if it can be added with its original attribute name as well) - Already present as renamed field "UserName"
TODO
[adForest] -> This would have to be customized since it's not a native attribute (Optional)
[adDomain] -> This would have to be customized since it's not a native attribute (Optional)

**Comment by AleAltube** [comment]
Hi Prashant,

I just tested the new version and it seems user attribute "Info" is not actually bringing the attribute's contents. Using PowerShell cmdlet I have validated there is content in this field for some users in the domain where I ran the script, but the CSV and Excel files show the entire Info column blank for all users.

Do you know what may be occurring?

Thanks again for the support!!!


________________________________

**Comment by prashant3535** [comment]
Hi AleAltube,

Could you please try now ? Also, could you test it with -Protocol LDAP ? Thanks

**Comment by prashant3535** [comment]
Lemme see if I can replicate it. Which version of powershell and office are you using ?

**Comment by AleAltube** [comment]
PowerShell:

Name                           Value
----                           -----
PSVersion                      5.1.16299.785
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.785
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


Office:
Name                                                                     Version
Microsoft Office OSM MUI (English) 2013                                  15.0.4569.1506
Microsoft Office Shared Setup Metadata MUI (English) 2013                15.0.4569.1506
Microsoft Office Shared 64-bit Setup Metadata MUI (English) 2013         15.0.4569.1506
Microsoft Office 64-bit Components 2013                                  15.0.4569.1506
Microsoft Office Shared 64-bit MUI (English) 2013                        15.0.4569.1506
Microsoft Office Proofing (English) 2013                                 15.0.4569.1506
Microsoft Office Shared MUI (English) 2013                               15.0.4569.1506
Microsoft Office Proofing Tools 2013 - English                           15.0.4569.1506
Microsoft Office Proofing Tools 2013 - Español                           15.0.4569.1506
Outils de vérification linguistique 2013 de Microsoft Office - Français  15.0.4569.1506
Office 16 Click-to-Run Extensibility Component                           16.0.8431.2299
Office 16 Click-to-Run Localization Component                            16.0.8326.2076
Office 16 Click-to-Run Localization Component                            16.0.8326.2076
Office 16 Click-to-Run Localization Component                            16.0.8326.2076
Office 16 Click-to-Run Extensibility Component 64-bit Registration       16.0.8431.2299
Office 16 Click-to-Run Licensing Component                               16.0.8431.2299
Microsoft Visual Studio 2010 Tools for Office Runtime (x64)              10.0.50908


________________________________

**Comment by prashant3535** [comment]
Do you have any entry in the ComputerSPNs.csv file with a very long value in the Host column ?

**Comment by AleAltube** [comment]
Im just running -collect users, no spns csv is generated, could the issue be long values within the info user field?

Thanks!

On 3 Dec 2018, at 21:37, prashant3535 <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have any entry in the ComputerSPNs.csv file with a very long value in the Host column ?

**Comment by prashant3535** [comment]
Yes, that is the issue (too long info field). Let me see how I can solve it.

**Comment by AleAltube** [comment]
U da man 😁

On 4 Dec 2018, at 09:04, prashant3535 <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, that is the issue (too long info field). Let me see how I can solve it.

**Comment by AleAltube** [comment]
Hey Prashant,

Any luck with this issue?


On 4 Dec 2018, at 09:04, prashant3535 <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, that is the issue (too long info field). Let me see how I can solve it.

**Comment by prashant3535** [comment]
Hey AleAltube, 

I pushed a potential bug fix for it last week. Are you still having the same issue ?

**Comment by AleAltube** [comment]
I did not see the update, my bad.
Will check early on tomorrow!

Thanks!

On 11 Dec 2018, at 22:45, prashant3535 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey AleAltube,

I pushed a potential bug fix for it last week. Are you still having the same issue ?

**Comment by AleAltube** [comment]
Hey Prashant,

Issue is fixed it seems, pivot table looks perfect, and Info column shows the appropriate content!

Note: I see an error, but it doesn't seem to be affecting the output:

PS C:\Users\alejandro.altube\Desktop\AD Recon - December 10th\ADRecon-master> $Env:PSExecutionPolicyPreference = 'Bypass' ; .\ADRecon.ps1 -DomainController ******** -Credential ********* -Collect users -OutputType Excel
[*] ADRecon v1.1 by Prashant Mahajan (@prashant3535)
[*] Running on *********** - Member Workstation
[*] Commencing - 12/12/2018 14:01:27
[-] Users - May take some time
[*] Total Execution Time (mins): 0.61
[*] Output Directory: C:\Users\alejandro.altube\Desktop\AD Recon - December 10th\ADRecon-master\ADRecon-Report-20181212140127
[*] Generating ADRecon-Report.xlsx
Remove-Variable : Cannot find a variable with the name 'Columns'.
At C:\Users\alejandro.altube\Desktop\AD Recon - December 10th\ADRecon-master\ADRecon.ps1:4315 char:9
+         Remove-Variable Columns
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Columns:String) [Remove-Variable], ItemNotFoundException
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand

[+] Excelsheet Saved to: C:\Users\alejandro.altube\Desktop\AD Recon - December 10th\ADRecon-master\ADRecon-Report-20181212140127\ADRecon-Report.xlsx


Thank you so much for your support!


________________________________
